### ISSUE TITLE
In the browser title span

### ISSUE THREAD

**Issue by Azizkz** [drmenzelit/Joomla-Plugin-Title-Change#3]
How to remove from the browser's browser?
![6](https://user-images.githubusercontent.com/31212661/29521441-5d9bf892-86a7-11e7-9add-8523e2937f31.jpg)

http://24.kz/ru/news/sport/item/192533-tyazheloatlet-albert-linder-prines-kazakhstanu-pervoe-zoloto-s-rekordom-universiady

**Comment by drmenzelit** [comment]
Thank you for the bug report. I will check this asap.

**Comment by drmenzelit** [comment]
Can you please the new version of the plugin? I think, the problem is now solved.

**Comment by Azizkz** [comment]
Thank you! Now everything is OK
